wandb_version: 1

train_attr:
  desc: null
  value: 'no'
pretrained:
  desc: null
  value: ''
_wandb:
  desc: null
  value:
    python_version: 3.9.7
    cli_version: 0.17.8
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725145051
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 4
      - 13
      - 16
      - 23
      - 42
      4: 3.9.7
      5: 0.17.8
      6: 4.24.0
      8:
      - 5
      13: linux-x86_64
